//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FCManager.rc
//
#define IDC_SELECT                      3
#define IDC_MOVE_UP                     4
#define IDC_MOVE_DOWN                   5
#define IDR_APPICON                     10
#define IDR_APPMENU                     11
#define IDR_APPACCEL                    12
#define IDR_APPTOOLBAR                  13
#define IDB_VIEWS                       20
#define IDR_OPTIONS_MENUS               30
#define ID_FILE_POPUP                   100
#define ID_FILE_NEW                     101
#define ID_FILE_OPEN                    102
#define ID_FILE_SAVE                    103
#define ID_FILE_SAVEAS                  104
#define ID_FILE_CLOSE                   105
#define ID_FILE_MRU_1                   106
#define ID_FILE_MRU_2                   107
#define ID_FILE_MRU_3                   108
#define ID_FILE_MRU_4                   109
#define ID_FILE_EXIT                    110
#define ID_VIEW_POPUP                   200
#define ID_VIEW_MEMBERS                 201
#define ID_VIEW_FIXTURES                202
#define ID_VIEW_SUBS                    203
#define ID_VIEW_BALANCE                 204
#define ID_VIEW_TEAM_SEL                205
#define ID_VIEW_OPPONENTS               206
#define ID_VIEW_REFEREES                207
#define ID_CLUB_FIXTURE                 230
#define ID_CLUB_POPUP                   300
#define ID_CLUB_DETAILS                 301
#define ID_CLUB_EXPENSES                302
#define ID_OPTIONS_POPUP                400
#define ID_OPTIONS_ADD                  401
#define ID_OPTIONS_EDIT                 402
#define ID_OPTIONS_DELETE               403
#define ID_OPTIONS_PRINT                404
#define ID_OPTIONS_IMPORT               405
#define ID_OPTIONS_EXPORT               406
#define ID_REPORTS_POPUP                500
#define ID_REPORTS_MEMBERS              501
#define ID_REPORTS_CUSTOM               502
#define ID_DEBUG_POPUP                  800
#define ID_DEBUG_DBCLIPBOARD            801
#define ID_DEBUG_DBFILE                 802
#define ID_HELP_POPUP                   900
#define ID_HELP_ABOUT                   901
#define IDC_SURNAME                     1004
#define IDC_FORENAME                    1005
#define IDC_POSTAL_ADDRESS              1006
#define IDC_EMAIL_ADDRESS               1009
#define IDC_NOTES                       1010
#define IDC_ADD_CREDIT                  1011
#define IDC_STATS                       1011
#define IDC_GROUND                      1012
#define IDC_EDIT_CREDIT                 1012
#define IDC_STD_COLOURS                 1013
#define IDC_DEL_CREDIT                  1013
#define IDC_DATE                        1014
#define IDC_ALT_COLOURS                 1015
#define IDC_ADD_DEBIT                   1015
#define IDC_EDIT_DEBIT                  1016
#define IDC_DEL_DEBIT                   1017
#define IDC_REFEREE                     1018
#define IDC_RESULT                      1019
#define IDC_AWAY_TEAM                   1020
#define IDC_HOME_TEAM                   1021
#define IDC_REGISTERED                  1022
#define IDC_TYPE                        1022
#define IDC_SENIOR                      1023
#define IDC_USUAL_TEAM                  1024
#define IDC_USUAL_POS                   1025
#define IDC_CLUB_NAME                   1027
#define IDC_SEASON                      1028
#define IDC_STD_PHONE                   1031
#define IDC_ALT_PHONE                   1032
#define IDC_GRID                        1033
#define IDC_NAME                        1034
#define IDC_CREDIT                      1037
#define IDC_CREDITS                     1038
#define IDC_PAID                        1038
#define IDC_DEBIT                       1041
#define IDC_DEBITS                      1042
#define IDC_MEMBERS                     1045
#define IDC_FEE                         1046
#define IDC_PRINTER                     1047
#define IDC_PORT                        1048
#define IDC_NO_CREDIT                   1049
#define IDC_FIXED_CREDIT                1050
#define IDC_VARIABLE_CREDIT             1051
#define IDC_PITCH                       1051
#define IDC_NO_DEBIT                    1052
#define IDC_FIXED_DEBIT                 1053
#define IDC_PLAYER                      1053
#define IDC_VARIABLE_DEBIT              1054
#define IDC_TEAM_FILTER                 1055
#define IDC_POSITION_FILTER             1056
#define IDC_FORMATION_LABEL             1057
#define IDC_FORMATION                   1058
#define IDC_OPPONENT                    1059
#define IDC_TAB_CTRL                    1060
#define IDC_NEW                         1063
#define IDC_TYPES                       1063
#define IDC_ADD                         1064
#define IDC_PAYMENTS                    1064
#define IDC_EDIT                        1065
#define IDC_VALUE                       1065
#define IDC_DELETE                      1066
#define IDC_STATISTICS                  1066
#define IDC_COLUMNS                     1068
#define IDD_ABOUT                       5000
#define IDD_GRID_VIEW                   5001
#define IDD_MEMBER                      5002
#define IDD_FIXTURE                     5003
#define IDD_FIXTURE_PAGE                5003
#define IDD_OPPONENT                    5004
#define IDD_OPPONENT_PAGE               5004
#define IDD_REFEREE                     5005
#define IDD_TEAM_SELS                   5006
#define IDD_CLUB_DETAILS                5007
#define IDD_NOTES                       5008
#define IDD_BALSHEET_ITEM               5009
#define IDD_BALSHEET_PAGE               5009
#define IDD_MEMBER_SUBS                 5010
#define IDD_PRINT_VIEW                  5011
#define IDD_PROPERTY                    5012
#define IDD_NOTES_PAGE                  5013
#define IDD_STATS_PAGE                  5014
#define IDD_NAME_PAGE                   5015
#define IDD_MEMSTATUS_PAGE              5016
#define IDD_INCOME_PAGE                 5017
#define IDD_EXPENSES_PAGE               5018
#define IDD_PAYMENTS_PAGE               5019
#define IDD_STATISTIC                   5020
#define ID_MEMBERS_POPUP                10000
#define ID_MEMBERS_ADD                  10001
#define ID_MEMBERS_EDIT                 10002
#define ID_MEMBERS_DELETE               10003
#define ID_MEMBERS_PRINT                10004
#define ID_MEMBERS_IMPORT               10005
#define ID_MEMBERS_EXPORT               10006
#define ID_FIXTURES_POPUP               10100
#define ID_FIXTURES_ADD                 10101
#define ID_FIXTURES_EDIT                10102
#define ID_FIXTURES_DELETE              10103
#define ID_FIXTURES_PRINT               10104
#define ID_FIXTURES_IMPORT              10105
#define ID_FIXTURES_EXPORT              10106
#define ID_SUBS_POPUP                   10200
#define ID_SUBS_PRINT                   10204
#define ID_BALSHEET_POPUP               10300
#define ID_BALSHEET_ADD                 10301
#define ID_BALSHEET_EDIT                10302
#define ID_BALSHEET_DELETE              10303
#define ID_BALSHEET_PRINT               10304
#define ID_TEAMSEL_POPUP                10400
#define ID_TEAMSEL_ADD                  10401
#define ID_TEAMSEL_EDIT                 10402
#define ID_TEAMSEL_DELETE               10403
#define ID_TEAMSEL_PRINT                10404
#define ID_OPPONENTS_POPUP              10500
#define ID_OPPONENTS_ADD                10501
#define ID_OPPONENTS_EDIT               10502
#define ID_OPPONENTS_DELETE             10503
#define ID_OPPONENTS_PRINT              10504
#define ID_OPPONENTS_IMPORT             10505
#define ID_OPPONENTS_EXPORT             10506
#define ID_REFEREES_POPUP               10600
#define ID_REFEREES_ADD                 10601
#define ID_REFEREES_EDIT                10602
#define ID_REFEREES_DELETE              10603
#define ID_REFEREES_PRINT               10604
#define ID_REFEREES_IMPORT              10605
#define ID_REFEREES_EXPORT              10606
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        229
#define _APS_NEXT_COMMAND_VALUE         238
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           200
#endif
#endif
